services:
  - type: web
    name: zenark-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: OPENAI_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: MONGO_DB_OFFICIAL
        sync: false
      - key: MONGO_DB_NAME_OFFICIAL
        sync: false
